#!/usr/bin/perl -w

# this here script toggles between the cpufreq governors.

#
# here is sample output from 'cpufreq-info -p':
#
#   600000 1600000 conservative
#

my $getcur = "/usr/bin/cpufreq-info -p";
my $set = "/usr/bin/sudo cpufreq-set -g";

# define order
my %next_after;
my $i = 1;
my @govs = ('performance', 'powersave', 'conservative');
for (@govs) { $next_after{$_} = $govs[$i++ % @govs] }

# wantarray
my ($cur) = (`$getcur` =~ /([a-z]+)/);

system "$set $next_after{$cur}";
print "Using $next_after{$cur}\n";
