#!/bin/bash

die () {
    2>&1 echo "$@"
    exit 1
}

self=$(basename $0)

case $(hostname) in
    fuzzbomb)
        builtin=eDP1
        external=HDMI2
        ;;
    *)
        die "Unknown computer"
        ;;
esac

d_external () {
    xrandr --output $external --auto
    xrandr --output $builtin --off
}

d_both () {
    xrandr --output $external --auto
    xrandr --output $builtin --below $external --auto
}

d_builtin () {
    xrandr --output $builtin --auto
    xrandr --output $external --off
}

auto () {
    if [ $(xrandr | grep \\bconnected | wc -l) -ne 2 ]; then
        die "Connect an external device before cycling to it!"
    fi

    status=$(
        xrandr |
        gawk "
            \$1 ~ /$builtin/ { m=\"builtin\" }
            \$1 ~ /$external/ { m=\"external\"}
            /\*/ { p[m] = 1 }
            END {
                for (idx in p)
                    print idx
            }"
    )

    if [ "$status" = "external" ]; then
        d_both
    elif [ $(wc -w <<<$status) -eq 2 ]; then
        d_builtin
    elif [ "$status" = "builtin" ]; then
        d_external
    else
        die "Unknown status: '$status'"
    fi
}

halp () {
    echo ""
    echo "$self [MODE]"
    echo ""
    echo "    Toggle displays: both -> external -> builtin -> both"
    echo "    Or, pick one in particular with: $self MODE"
    echo ""
}

case "$1" in
    both|external|builtin)
        d_$1
        ;;
    "")
        auto
        ;;
    -h|--help)
        halp
        ;;
    *)
        2>&1 halp
        exit 1
        ;;
esac
