#!/usr/bin/env bash

set -e

log=~/Syncthing/PhoneFiles/Log.txt

if [ -n "$(ls ~/Syncthing/PhoneFiles/.Log.txt.sw? 2>/dev/null)" ]; then
    >&2 echo "Swap files exist!"
    >&2 ls ~/Syncthing/PhoneFiles/.Log.txt.sw?
    exit 1
fi

name_window () {
    if [ -n "$TMUX" ]; then
        tmux rename-window day
    fi
}

unname_window () {
    if [ -n "$TMUX" ]; then
        tmux set automatic-rename on >/dev/null
    fi
}

trap unname_window EXIT
name_window
vim $log +'normal GzoGzt' +'Goyo 100' +Timestamp
