#!/usr/bin/env bash

set -e

log=~/Documents/Log.txt
date=`ddate`
time=`date +%H:%M`

if [ -n "$(ls ~/Documents/.Log.txt.sw? 2>/dev/null)" ]; then
    >&2 echo "Swap files exist!"
    >&2 ls ~/Documents/.Log.txt.sw?
    exit 1
fi

(
    exec >>$log

    [ "`tail -n 1 $log`" = "" ] || echo ""
    if ! grep -q $date <$log ; then
        echo -e "${date}\n------\n"
    fi
    echo -e "${time}: "
)

if [ -n "$TMUX" ]; then
    tmux rename-window day
fi

# '+' means 'cursor at last line'
vim + $log +'normal zt' +Goyo +startinsert\!

if [ -n "$TMUX" ]; then
    tmux set automatic-rename on >/dev/null
fi

