#!/usr/bin/env bash

# Various quick date formats
if [ "$1" = "-1" ]; then
    shift
    date '+%Y-%m-%d' $@ | perl -pe 'chomp'
elif [ "$1" = "-t" ]; then
    shift
    date '+%H:%M' $@ | perl -pe 'chomp'
else
    date '+%Y%m%d' $@
fi
