#!/usr/bin/python

import sys

if len(sys.argv) > 1 and sys.argv[1] == "barobo":
  user = "barobo"
else:
  user = "personal"

from keyring import get_password

print(get_password(sys.argv[1], sys.argv[2]))
