#!/bin/bash
#
# TWO MODES
# 
# with -R:
#   1. Show albums at random, for some value of random.
#   2. Give four options: skip, listen, delete, quit
#   3. Adjust the album's score.
#   4. Take the appropriate action (trash, listen, etc)
#
# with album specified on command line:
#
#   1. Adjust album's score
#   2. Play album.

_TESTING_=false
_TEST_ALBUM_="/home/b/Music/In_Flames/Whoracle"

shopt -s extglob

play_with_args () {
    args=$1
    shift
    mpg123 $args --title --cpu SSE "$@" 2>&1 | tee -a ~/Music/err.log
    echo "Goodness, $?" >> ~/Music/err.log
}

play_album () {
    play_with_args "-Cb 2048" "$@"
}

play_sample () {
    play_with_args "-qn 400" "$@"
}

record () {
    $_TESTING_ ||
        echo "$@ $(date +%Y:%m:%d:%H:%M)" >> ~/Music/randmusic.log
}

manual_play () {
    record $1 m
    play_album "$1"/*
}

play () {
    record $1 y
    play_album "$1"/*
}

skip () {
    record $1 n
}

delete () {
    read -p "Really delete $1? Type 'yes' to confirm: " conf
    if [ $conf = "yes" ]; then
        record $1 deleted
        rm -r $1
    fi
    find ~/Music -empty -delete
}

kill_sample () {
    # Use INT, the 'keyboard interrupt', because bash doesn't display the
    # 'Terminated' message when it's used.
    pkill -INT mpg123
}

rand_music () {
    song_list_file=`tempfile`
    trap "rm -f $song_list_file" EXIT

    leafdir ~/Music | sort -R > $song_list_file
    exec 5<$song_list_file

    while read album <&5; do
        $_TESTING_ && [ -n "$_TEST_ALBUM_" ] &&
            album=$_TEST_ALBUM_
        clear
        cat <<-EOF
-------------------------------------------------------------------------------
$album
-------------------------------------------------------------------------------
`ls -1 "$album"`

EOF
        first_song=$(ls -1 "$album" | head -n 1)
        play_sample "$album/$first_song" &
        retry=true
        while $retry; do 
            read -n1 -p"? " cmd
            echo
            retry=false
            case $cmd in
                y|p) kill_sample; play "$album";;
                n|s) kill_sample; skip "$album";;
                D)   kill_sample; delete "$album";;
                q)   kill_sample; break 2;;
                *)   retry=true;;
            esac
        done
    done
    trap - EXIT
    rm -f $song_list_file
    echo
}

$_TESTING_  && {
    echo "The varible _TESTING_ is set to true!"
    sleep 3
}

if [ $# = 1 ]; then
    if [ $1 = "-R" ]; then
        rand_music
    else 
        manual_play $1
    fi
else
    echo "I don't think you know what you're talking about."
    exit 2
fi
