#!/bin/bash

# Because ag doesn't have a way to say "always print filenames", tack on a
# dummy filename. But only if the last argument is a file.
if [ -f "${!#}" ]
then
    args="$@ /dev/null"
else
    args="$@"
fi
vim -q <(ag --column "$args")
