#!/bin/bash

## Display a list of folders
## Spawn a shell and drop to appropriate dir

# This is where all the tickler directories physically live. Modify to taste.
Filing_cabinet=~/Org/Tickler

#####
#####

# These two are indexed relative to today
declare -a Physical_dirs
declare -a Folder_names

main () {
    echo
    echo "** Using $Filing_cabinet as filing cabinet."
    echo
    sleep 1

    build_arrays

    collect_skipped_items
    
    select dir in "${Folder_names[@]}"; do
        if [ -n "$dir" ]; then
            let "i = REPLY - 1"
            physical_dir=${Physical_dirs[$i]}
            export PS1="[TICKLER] ${Folder_names[$i]}$ "
            mkdir -p $Filing_cabinet/$physical_dir
            cd $Filing_cabinet/$physical_dir
            bash --norc
            cd - >/dev/null
        fi
    done

    # Keep track of when we were run last
    echo "$(date -R)" >> $Filing_cabinet/last_run
}

build_arrays() {
    current_month=$(date +%B)
    # Use %-d so numbers aren't interpreted as octal (<-- errors on '08')
    next_month_index=$[32 - `date +%-d`]

    # i is input iterator, o is output iterator
    for ((i=0, o=0; o < 43; i++, o++)); do
        # First 32 inputs turn into days with 1 month interspersed
        if [ $i -lt 31 ]; then

            if [ $i -eq $next_month_index ]; then
                t="$current_month 1 + 1 month"
                add_month "$o" "$t"
                let o++
            fi

            t="today + $i day"
            Folder_names[$o]=$(date -d "$t" +"%b-%d")
            Physical_dirs[$o]=$(date -d "$t" +%Y%m%d)

        # Rest of inputs are months
        else
            t="$current_month 1 + $[$i - 29] month"
            add_month "$o" "$t"
        fi
    done

    # Now, make folders with contents stick out
    emphasize_nonempty_folders
}

collect_skipped_items () {
    # Last run time is determined by $Filing_cabinet/last_run's mod time. If
    # the last run was earlier than yesterday, we'll gather any/everything that
    # was skipped between that day and today.
    
    skipped_items=""

    yesterday=$(date +%s -d 'yesterday 4am')
    # The following computes to 4am on the day last_run was modified.
    last_run=$(
        date +%s \
             -d "$(date +'%Y-%m-%d 4am' \
                        -d "`stat -c %y $Filing_cabinet/last_run`")")

    if [ $(( $last_run_date - $yesterday )) -lt 0 ] ; then 
        for ((i = $last_run; i < $yesterday; i += 60*60*24)); do
            dir=$(date +%Y%m%d -d @$i)
            [ -d $Filing_cabinet/$dir ] && 
                skipped_items="$skipped_items $Filing_cabinet/$dir"
        done
    fi

    if [ -n "$skipped_items" ]; then
        echo "Skipped items found!"
        echo ""
        echo "    $skipped_items" | par
        echo ""
        sleep 1

        dump_dir="$Filing_cabinet/$(date +%Y%m%d)/skipped_items"
        mkdir -p $dump_dir
        cp -r $skipped_items $dump_dir
    fi
}

add_month () {
    o=$1; t=$2;
    Folder_names[$o]=$(date -d "$t" +%B)
    Physical_dirs[$o]=$(date -d "$t" +%Y%m)
}

emphasize_nonempty_folders () {
    # Easiest just to remove empty folders. :)
    find $Filing_cabinet -empty -delete

    for ((i=0; i<43; i++)); do
        if [ -e "${Filing_cabinet}/${Physical_dirs[$i]}" ]; then
            Folder_names[$i]=${Folder_names[$i]}" (!)"
        fi
    done
}

main
