#!/bin/bash

if [ -e _darcs ]; then
    darcs wha 
elif [ -e .CVS ]; then
    cvs update
elif git status >/dev/null 2>&1; then
    git st || git status
else
    >&2 echo "No (known) repo found here."
    exit 2
fi
