#!/bin/bash

## Set wm.
# The following should simply be:
#     . <(grep ^wm= ~/.Xsession) 
# But this is broken.
tmp=`mktemp`
grep ^wm= ~/.Xsession > $tmp
. $tmp
rm $tmp
unset tmp

# On with the show.

wm_pid=`ps x -o 'command,pid' | grep ^$wm | awk '{print $2}'`
pstree -U $wm_pid

